version: "3.8"

volumes:
  postgres-db:
  redis:

networks:
  backend:
    driver: bridge

services:
  app:
    container_name: ${APP_CONTAINER_NAME}
    build:
      context: docker/app
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${APP_HOST_PORT}:${APP_CONTAINER_PORT}
    volumes:
      - .:/usr/src/app
    command: sh -c "sleep 10 && air ./cmd/apiserver/main.go"
    depends_on:
      - db
      - redis
      - stan
    networks:
      - backend

  db:
    container_name: ${DB_CONTAINER_NAME}
    build:
      context: docker/db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_HOST_PORT}:${DB_CONTAINER_PORT}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    container_name: ${REDIS_CONTAINER_NAME}
    build:
      context: docker/redis
      dockerfile: Dockerfile
    ports:
      - ${REDIS_HOST_PORT}:${REDIS_CONTAINER_PORT}
    volumes:
      - redis:/usr/local/etc/redis
    networks:
      - backend

  stan:
    container_name: ${STAN_CONTAINER_NAME}
    build:
      context: docker/stan
      dockerfile: Dockerfile
    networks:
      - backend

